<?php

namespace Inovector\Mixpost\SocialProviders\Farminsta;

use App\Commands\UserCreatesReelCommand;
use App\Models\Reel;
use App\Services\LinkService;
use Closure;
use Illuminate\Support\Collection;
use Inovector\Mixpost\Abstracts\SocialProvider;
use Inovector\Mixpost\Contracts\SocialProviderPostOptions as SocialProviderPostOptionsContract;
use Inovector\Mixpost\Enums\SocialProviderResponseStatus;
use Inovector\Mixpost\Models\Media;
use Inovector\Mixpost\Support\SocialProviderPostConfigs;
use Inovector\Mixpost\Support\SocialProviderResponse;
use Inovector\Mixpost\Util;

class FarminstaProvider extends SocialProvider
{

    public static function service(): string
    {
        return 'Farminsta';
    }

    public function getAuthUrl(): string
    {
        return "";
    }

    public function requestAccessToken(array $params): array
    {
        return [];
    }

    public function buildResponse($response, Closure $okResult = null): SocialProviderResponse
    {
        return new SocialProviderResponse(SocialProviderResponseStatus::OK, []);
    }

    public function getAccount(): SocialProviderResponse
    {
        return new SocialProviderResponse(SocialProviderResponseStatus::OK, []);
    }

    public function publishPost(string $text, Collection $media, array $params = []): SocialProviderResponse
    {
        \Log::error(json_encode([
            $text,
            $media,
            $media->first()->getUrl(),
            $params,
            $this->values,
        ], JSON_PRETTY_PRINT));


        $channel_id = $this->values['provider_id'];
        $user_id = $this->values['data']['user_id'];
        $link = app()->make(LinkService::class)->generateLink($user_id, 'https://app.farminsta.com/', 'invite')->getFullUrl();

        /** @var Media $video */
        $video = $media->first();

        $medias = $media->reduce(function ($acc, $item) {
            /** @var Media $item */
            if ($item->isVideo()) {
                $acc['video'] = $item;
            } else if ($item->isImage()) {
                $acc['thumbnail'] = $item;
            }
            return $acc;
        }, ['video' => null, 'thumbnail' => null]);

        $video = $medias['video'] ?? null;
        $thumbnail = $medias['thumbnail'] ?? null;

        $command = new UserCreatesReelCommand(
            $user_id,
            $video->getUrl(),
            $params['title'],
            $params['description'],
            '#farminsta',
            $params['category_id'],
            null,
            'en_in',
            null,
            null,
            true,
            true,
            true,
            true,
            true,
            true,
            0,
            0,
            null,
            null,
            null,
            [],
            $channel_id,
            false,
        );

        $responses = \Event::dispatch($command);
        $reel = Reel::whereS3Path($video->getUrl())->first();

        \Log::error(json_encode($responses));
        \Log::error(json_encode($media));
        \Log::error(json_encode($reel));

        return new SocialProviderResponse(SocialProviderResponseStatus::OK, [
            'id' => $reel?->id,
        ]);

    }

    public function deletePost($id): SocialProviderResponse
    {
        return new SocialProviderResponse(SocialProviderResponseStatus::OK, []);
    }

    public static function postConfigs(): SocialProviderPostConfigs
    {
        return SocialProviderPostConfigs::make()
            ->simultaneousPosting(true)
            ->minTextChar(0)
            ->maxTextChar(100)
            ->minVideos(1)
            ->maxPhotos(1)
            ->maxVideos(1)
            ->maxGifs(0)
            ->allowMixingMediaTypes(true);
    }

    public static function postOptions(): SocialProviderPostOptionsContract
    {
        return parent::postOptions(); // TODO: Change the autogenerated stub
    }
}
